
// Function to generate a downloadable PDF report
export const generateReport = (results: any) => {
  // In a real implementation, this would use jsPDF or a similar library
  // For demo purposes, we'll create a simple text report and trigger a download
  
  const { 
    resumeFileName, 
    keywordMatches, 
    atsScore, 
    keywordMatchPercentage, 
    interviewProbability,
    missingKeywords,
    sectionScore,
    industryRelevanceScore,
    formatting,
    contactInfo,
    education,
    penalties,
    contextMatch
  } = results;
  
  // Generate personalized recommendations
  const recommendations = [];
  
  // Keyword recommendations
  if (missingKeywords.length > 0) {
    recommendations.push(`Add Missing Keywords: Include these key terms: ${missingKeywords.slice(0, 5).join(', ')}${missingKeywords.length > 5 ? '...' : ''}`);
  }
  
  // Format recommendations
  if (!formatting?.hasBulletPoints) {
    recommendations.push("Use Bullet Points: Break up dense paragraphs with bullet points to improve scannability");
  }
  
  if (!formatting?.hasQuantifiableAchievements) {
    recommendations.push("Add Quantifiable Achievements: Include numbers and percentages to showcase your impact");
  }
  
  if (formatting?.actionVerbsScore < 5) {
    recommendations.push("Use Strong Action Verbs: Start bullet points with powerful verbs like 'achieved', 'launched', etc.");
  }
  
  // Structure recommendations
  if (sectionScore < 10) {
    recommendations.push("Improve Section Structure: Include standard sections like Experience, Education, Skills, and Projects");
  }
  
  // Contact info recommendations
  if (!contactInfo?.hasLinkedIn) {
    recommendations.push("Add LinkedIn Profile: Include your LinkedIn URL to provide more context about your experience");
  }
  
  if (!contactInfo?.hasPortfolio && keywordMatchPercentage < 60) {
    recommendations.push("Add Portfolio/Github Link: Include links to your work to demonstrate your skills directly");
  }
  
  // Length recommendation
  if (penalties?.lengthPenalty < 0) {
    recommendations.push(penalties.lengthPenalty === -10 
      ? "Optimize Resume Length: Your resume appears too short. Expand on your experience and skills."
      : "Optimize Resume Length: Your resume may be too long. Focus on the most relevant information.");
  }
  
  // Formatting penalty recommendations
  if (penalties?.formattingPenalty < 0) {
    recommendations.push("Simplify Formatting: Remove complex formatting that may confuse ATS systems");
  }
  
  // Make sure we have at least some recommendations
  if (recommendations.length === 0) {
    recommendations.push("Finalize Your Resume: Your resume looks great! Consider having it professionally proofread once more.");
  }
  
  // Generate report content
  const reportContent = `
ATS SCAN REPORT
-----------------
Resume: ${resumeFileName}
Date: ${new Date().toLocaleDateString()}

SCORES
-----------------
ATS Compatibility Score: ${atsScore}%
Keyword Match: ${keywordMatchPercentage}%
Interview Probability: ${interviewProbability}%

SCORE BREAKDOWN
-----------------
Section Structure: +${sectionScore || 0} points
Industry Relevance: +${industryRelevanceScore || 0} points
Action Verb Usage: +${formatting?.actionVerbsScore || 0} points
Contact Info: +${contactInfo?.score || 0} points
Education Details: +${education?.score || 0} points
Formatting Issues: ${penalties?.formattingPenalty || 0} points
Resume Length: ${penalties?.lengthPenalty || 0} points

KEYWORD ANALYSIS
-----------------
${Object.entries(keywordMatches)
  .map(([keyword, found]) => `${found ? '✓' : '✗'} ${keyword}`)
  .join('\n')
}

MISSING KEYWORDS
-----------------
${missingKeywords.length > 0 
  ? missingKeywords.join(', ') 
  : 'None! Great job - your resume contains all the important keywords.'}

PERSONALIZED RECOMMENDATIONS
-----------------
${recommendations.map((rec, index) => `${index + 1}. ${rec}`).join('\n')}

IMPROVEMENT TIPS
-----------------
1. Tailor your resume for each job application
2. Use industry-standard section headers
3. Save your resume as a standard PDF with selectable text
4. Include a skills section with both technical and soft skills
5. Remove images, icons, and complex formatting that may confuse ATS systems

IMPORTANT NOTES
-----------------
* Interview probability is heavily influenced by keyword match percentage
* A keyword match below 40% significantly reduces chances of getting past ATS
* Using industry-specific terminology relevant to the position is crucial
* Recruiters typically spend less than 10 seconds on each resume that passes the ATS

Report generated by ATS ProScan - No data is stored or sent to any server.
All processing is done locally in your browser.
  `;
  
  // Create a blob with the report content
  const blob = new Blob([reportContent], { type: 'text/plain' });
  
  // Create a URL for the blob
  const url = URL.createObjectURL(blob);
  
  // Create a link element
  const a = document.createElement('a');
  a.href = url;
  a.download = `ATS_Scan_Report_${new Date().toLocaleDateString().replace(/\//g, '-')}.txt`;
  
  // Append to the body
  document.body.appendChild(a);
  
  // Trigger the download
  a.click();
  
  // Clean up
  URL.revokeObjectURL(url);
  document.body.removeChild(a);
};
